services:
  - type: web
    name: chitchat-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 7777
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_TOKEN
        sync: false
      - key: FRONTEND_URL
        sync: false
